name: 11
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'true/false'
jobs:

  build_openwrt:

    name: 111

    runs-on: ubuntu-latest
    
    steps:

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          
          curl "https://api.telegram.org/bot6026352946:AAE9U1pdikRmpOSsVejRjx41ddBf9W__1OY/sendMessage?chat_id=1382259195&text=test123"
