
# This is a basic workflow to help you get started with Actions

name: usb-openwrt

# Controls when the workflow will run
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'true/false'
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
     
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          wget https://github.com/ventoy/OpenWrtPlugin/releases/download/v1.0/ventoy_openwrt_squashfs.sh
          echo test, and deploy your project.
      - name: Upload firmware to cowtransfer

        run: |

          curl -sL https://git.io/file-transfer | sh

          ./transfer cow --cookie="remember-mev2=MTgwMzI2OTYzMzA6MTY3OTMyMDY1NjAxNzphY2E2ZGNhMzZiNjlhNWFmNzY0Mzc4ZjZmNWVmNmJkZA" -a "<eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJndWlkIjoiN2I2ZTE4NzQtNDk5Ni00ODE4LTkwMjgtNGRmYTUzNjgxNGQwIiwiZXhwIjoxNjc4NzE1ODU2fQ.xJEpEqoKdchNE5vXkqraIdvCgn1aSg22gNYHOEwcUxw>" --block 2621440 -s -p 64 --no-progress ./lede/bin/targets

    
